defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
        address = ":80"
        [entryPoints.http.redirect]
            entryPoint = "https"
    [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]

[acme]
email = "kino@fynn-weyrich.de"
storage = "acme.json"
entryPoint = "https"
onHostRule = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "gang-of-fork.de"
watch = true
network = "infrastruktur_default"

[acme.httpChallenge]
entryPoint = "http"

[[acme.domains]]
main = "fitnessapp.gang-of-fork.de"
sans = ["api.fitnessapp.gang-of-fork.de"]

[[acme.domains]]
main = "learning-analytics.gang-of-fork.de"
sans = ["api.learning-analytics.gang-of-fork.de"]

[[acme.domains]]
main =  "plantexchange.gang-of-fork.de"
sans = ["api.plantexchange.gang-of-fork.de"]

[[acme.domains]]
main =  "example.odatafy.gang-of-fork.de"