name: Copy Hosting to Server

on:
  push:
    branches: [ main ]
    paths:
      - "hosting/**"
      - ".github/workflows/**"


jobs:
  deploy:
    name: Copy files to Server
    runs-on: ubuntu-latest

    steps:
 
      - uses: actions/checkout@master

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./hosting/docker-compose.yml, ./hosting/traefik.toml"
          target: "~/"
      
      - name: Apply docker-compose changes
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PORT: ${{ secrets.SSH_PORT }}
          script: |
            # login to ghcr
            echo ${{secrets.SSH_PASSWORD}} | sudo -S docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN}}
            # restart containers, if neccessary
            sudo -S BACKEND_PORT=${{ secrets.BACKEND_PORT }} DB_URL=${{ secrets.DB_URL}} docker-compose -f ./hosting/docker-compose.yml up -d --force-recreate