name: Copy Hosting to Server

on:
  push:
    branches: [ main ]
    paths:
      - "hosting/**"


jobs:
  deploy:
    name: Copy files to Server
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./hosting/docker-compose.yaml, ./hosting/traefik.toml"
          target: "~/"
      
      - name: Apply docker-compose changes
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PORT: ${{ secrets.SSH_PORT }}
          script: |
            # enter sudo password
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S echo helloworld
            # login to ghcr
            echo ${{secrets.GITHUB_TOKEN}} | sudo docker login ghcr.io -u lumaghg --password-stdin 
            # restart containers, if neccessary
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S \
            #add env variable secrets here
            docker-compose -f ./hosting/docker-compose.yaml up -d --force-recreate